# Generated by Django 3.2.3 on 2021-06-03 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('asset', models.BooleanField(verbose_name='Ativo')),
                ('liability', models.BooleanField(verbose_name='Passivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Se o tipo de pagamento é parcelado, esse é o valor real!', max_digits=11, verbose_name='Valor Total')),
                ('total_parcels', models.IntegerField(default=1, verbose_name='Parcelas Totais')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='financial_release', verbose_name='Anexo')),
                ('cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.costcenter', verbose_name='Centro de Custo')),
                ('type_of_payment', models.ForeignKey(help_text='If the type of payment is parceled out, you must provide the amount of parcels. The parcels will be created automatically!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.typeofpayment', verbose_name='Tipo de Pagamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
