# Generated by Django 3.2.3 on 2021-05-21 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='If the type of payment is parceled out, this is the real total!', max_digits=5, verbose_name='Total Value')),
                ('total_parcels', models.IntegerField(default=1, verbose_name='Total Parcels')),
                ('cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.costcenter', verbose_name='Cost Center')),
                ('type_of_payment', models.ForeignKey(help_text='If the type of payment is parceled out, you must provide the amount of parcels. The parcels will be created automatically!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.typeofpayment', verbose_name='Type of Payment')),
            ],
        ),
    ]
