# Generated by Django 3.2.3 on 2021-05-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='asset',
            field=models.BooleanField(verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='liability',
            field=models.BooleanField(verbose_name='Passivo'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='financialrelease',
            name='cost_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.costcenter', verbose_name='Centro de Custo'),
        ),
        migrations.AlterField(
            model_name='financialrelease',
            name='total_parcels',
            field=models.IntegerField(default=1, verbose_name='Parcelas Totais'),
        ),
        migrations.AlterField(
            model_name='financialrelease',
            name='total_value',
            field=models.DecimalField(decimal_places=2, help_text='Se o tipo de pagamento é parcelado, esse é o valor real!', max_digits=5, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='financialrelease',
            name='type_of_payment',
            field=models.ForeignKey(help_text='If the type of payment is parceled out, you must provide the amount of parcels. The parcels will be created automatically!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.typeofpayment', verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='typeofpayment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='typeofpayment',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
    ]
