# Generated by Django 3.2.3 on 2021-05-30 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20210525_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrelease',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='financial_release', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='financialrelease',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
