# Generated by Django 3.2.3 on 2021-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20210530_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrelease',
            name='total_value',
            field=models.DecimalField(decimal_places=2, help_text='Se o tipo de pagamento é parcelado, esse é o valor real!', max_digits=11, verbose_name='Valor Total'),
        ),
    ]
