# Generated by Django 3.2.3 on 2021-05-31 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_financialrelease_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrelease',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
