# Generated by Django 3.2.3 on 2021-05-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Value')),
                ('start_date', models.DateField(help_text='Date that the contract was signed/agreed.', verbose_name='Start Date')),
                ('expiration', models.IntegerField(default=12, help_text='Expiration of the contract in months.', verbose_name='Expiration')),
                ('description', models.TextField(verbose_name='Description')),
                ('attachment', models.FileField(upload_to='', verbose_name='Attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('link', models.TextField(verbose_name='Link')),
                ('acquisition_date', models.DateField(help_text='Date that the domain was buyed.', verbose_name='Acquisition Date')),
                ('contract', models.ManyToManyField(blank=True, to='service.Contract', verbose_name='Contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client')),
                ('contract', models.ManyToManyField(blank=True, to='service.Contract', verbose_name='Contract')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.domain', verbose_name='Domain')),
                ('type_of_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.typeofservice', verbose_name='Type of Service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
