# Generated by Django 3.2.3 on 2021-06-03 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(help_text='Um nome amigável para lembrar fácil.', max_length=32, verbose_name='Nome')),
                ('value', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor')),
                ('start_date', models.DateField(help_text='Data que o contrato foi assinado/acordado.', verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('expiration', models.IntegerField(default=12, help_text='Expiração do contrato em meses.', verbose_name='Expiração')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='Anexo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('link', models.TextField(verbose_name='Link')),
                ('acquisition_date', models.DateField(help_text='Data que o domínio foi comprado.', verbose_name='Data de Aquisição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contract', models.ManyToManyField(blank=True, to='service.Contract', verbose_name='Contrato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('color', models.CharField(default='#ffffff', max_length=7, verbose_name='Cor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Esta data é usada para estatísticas, construir gráficos. ', verbose_name='Data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Cliente')),
                ('contract', models.ManyToManyField(blank=True, to='service.Contract', verbose_name='Contrato')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.domain', verbose_name='Domínio')),
                ('type_of_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.typeofservice', verbose_name='Tipo de Serviço')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
