# Generated by Django 3.2.3 on 2021-05-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210525_1423'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expiration',
            field=models.IntegerField(default=12, help_text='Expiração do contrato em meses.', verbose_name='Expiração'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(help_text='Data que o contrato foi assinado/acordado.', verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='acquisition_date',
            field=models.DateField(help_text='Data que o domínio foi comprado.', verbose_name='Data de Aquisição'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='contract',
            field=models.ManyToManyField(blank=True, to='service.Contract', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='typeofservice',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='typeofservice',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='webservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='webservice',
            name='contract',
            field=models.ManyToManyField(blank=True, to='service.Contract', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='webservice',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.domain', verbose_name='Domínio'),
        ),
        migrations.AlterField(
            model_name='webservice',
            name='type_of_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.typeofservice', verbose_name='Tipo de Serviço'),
        ),
    ]
