# Generated by Django 3.2.3 on 2021-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210525_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor'),
        ),
    ]
