# Generated by Django 3.2.3 on 2021-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_contract_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
