# Generated by Django 3.2.3 on 2021-06-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210531_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofservice',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
