# Generated by Django 3.2.3 on 2021-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_typeofservice_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofservice',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Color'),
        ),
    ]
