# Generated by Django 3.2.3 on 2021-06-03 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, verbose_name='Telefone')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Aniversário')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Esta data é usada para estatísticas, construir gráficos. ', verbose_name='Data')),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.occupation', verbose_name='Ocupação')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
