# Generated by Django 3.2.3 on 2021-06-01 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='This date is used for statistics, build charts. ', verbose_name='Data'),
        ),
    ]
