# Generated by Django 3.2.3 on 2021-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('contract_warning_days', models.IntegerField(default=7, help_text='Dias que devem ser considerados para avisar um contrato expirado', verbose_name='Aviso Contrato Dias')),
                ('month_earn_goal', models.DecimalField(decimal_places=2, default=1, max_digits=11, verbose_name='Meta de Ganho Mensal')),
                ('year_earn_goal', models.DecimalField(decimal_places=2, default=1, max_digits=11, verbose_name='Meta de Ganho Anual')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
