# Generated by Django 3.2.3 on 2021-05-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_domain', models.BooleanField(default=True, help_text='Warning when a domain is near to expire.', verbose_name='Warning Domain')),
                ('show_financial_stats', models.BooleanField(default=True, help_text='Show the financial stats: Assets x Liability.', verbose_name='Show Financial Stats')),
                ('show_financial_graphs', models.BooleanField(default=True, help_text='Show graphs about the financial situation, just a resume about the current year. For more detailed info go to financial report.', verbose_name='Show Financial Graphs')),
            ],
        ),
    ]
