# Generated by Django 3.2.3 on 2021-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210531_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='contract_warning_days',
            field=models.IntegerField(default=7, help_text='Days that should be considered to warning a contract expired', verbose_name='Contract Warning Days'),
        ),
    ]
