# Generated by Django 3.2.3 on 2021-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboardsettings_contract_warning_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardsettings',
            name='show_financial_graphs',
        ),
        migrations.RemoveField(
            model_name='dashboardsettings',
            name='show_financial_stats',
        ),
        migrations.RemoveField(
            model_name='dashboardsettings',
            name='warning_domain',
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='month_earn_metric',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Month Earn Metric'),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='year_earn_metric',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Year Earn Metric'),
        ),
    ]
